### ISSUE TITLE
Carthage Installation: Unable to build for non-iOS (for Carlos)

### ISSUE THREAD

**Issue by UncleRic** [spring-media/PiedPiper#20]
*** Building scheme "PiedPiper" in PiedPiperSample.xcodeproj
Build Failed
	Task failed with exit code 70:
	/usr/bin/xcrun xcodebuild -project /Users/Ric/Software\ Development/BitBucket/carlos/Carthage/Checkouts/PiedPiper/PiedPiperSample.xcodeproj -scheme PiedPiper -configuration Release -derivedDataPath /Users/Ric/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10L221o/PiedPiper/b8bdd81c0a75955dae71654eaf65972b99c87ba8 -sdk watchsimulator -destination platform=watchOS\ Simulator,id=51840722-B8A1-473C-8A34-670A7F139903 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/Ric/Software Development/BitBucket/carlos/Carthage/Checkouts/PiedPiper)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/6w/fl6bb2fs2kdfbfxd2hz0cjr40000gn/T/carthage-xcodebuild.4Wj8Dh.log
$~/Software Development/bitbucket/carlos:

===============
Log snippet:

Build settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchsimulator5.0

xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:watchOS Simulator, id:51840722-B8A1-473C-8A34-670A7F139903 }

	The requested device could not be found because no available devices matched the request.
...
...
Ineligible destinations for the "PiedPiper" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
		{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Generic tvOS Device }
		{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Generic tvOS Simulator Device }
		{ platform:watchOS, id:dvtdevice-DVTiOSDevicePlaceholder-watchos:placeholder, name:Generic watchOS Device }
		{ platform:watchOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-watchsimulator:placeholder, name:Generic watchOS Simulator Device }

===============
I was able to build with the --platform iOS directive.

**Comment by ivanlisovyi** [comment]
I very long time passed but this issue shall not happen anymore with the **0.11.0** release 😅
