### ISSUE TITLE
Implement some + some-traverse dual

### ISSUE THREAD

**Issue by bkase** [spring-media/PiedPiper#9]
As mentioned in WeltN24/Carlos#154, it probably makes sense to supply a `some` and something equivalent to `traverse` but semantically a `some` rather than a `merge` after some mapping (I'll look for the proper name, but let me know if you know such a name already).

I'll add these in a pull-request soon

**Comment by vittoriom** [comment]
Hi @bkase, yes it would be a very nice thing to have. `some` is somehow too generic and one could confuse it with the `.Some` related to Swift `Optional`s. But I didn't find a better name yet.
Nevertheless, I thought about how to implement this when adding functional features to `PiedPiper` (`map`, `flatMap`, `reduce`, `merge` and so on), but as you can see [here](https://github.com/WeltN24/Carlos/blob/master/Carlos/CacheLevel%2BBatch.swift#L23) I didn't manage to improve the `batchGetSome` implementation. 
Do you already have something in mind for that?

**Comment by vittoriom** [comment]
maybe we can call the functions `mergeAll` and `mergeSome`, to mirror `batchAll` and `batchSome`?

**Comment by vittoriom** [comment]
I'll close this
